manifest_version = 2
name = "wld-multiplayer"
description = "WordLadder multiplayer layer for Discord"
authors = ["wld-team"]

[local_server]
  [local_server.backends]
    origin = { url = "https://discord.wordladder.fun" }

[setup]
  [setup.kv_stores]
    wld = {}

[env.local]
  ORIGIN = "https://discord.wordladder.fun"
